# Generated by Django 5.0.4 on 2024-04-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
    ]
